#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${DEMO_ENV_FILE:-$SCRIPT_DIR/local-demo.env}"
EXAMPLE_ENV_FILE="$SCRIPT_DIR/local-demo.env.example"

info() {
  printf '[demo] %s\n' "$*"
}

die() {
  printf '[demo][error] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<EOF
Usage:
  ./demo/local-role.sh init [--active-host HOST] [--active-port PORT] [--backup-host HOST] [--backup-port PORT]
  ./demo/local-role.sh show
  ./demo/local-role.sh active-core
  ./demo/local-role.sh backup-core
  ./demo/local-role.sh edge-a
  ./demo/local-role.sh edge-b
  ./demo/local-role.sh active-sub
  ./demo/local-role.sh backup-sub
  ./demo/local-role.sh clear-retained

What this script does:
  - keeps one local demo topology config in $ENV_FILE
  - requires only active/backup core host:port to be customized
  - derives edge commands automatically from that config

Typical flow:
  1. ./demo/local-role.sh init --active-host 127.0.0.1 --active-port 1883 --backup-host 127.0.0.1 --backup-port 1884
  2. ./demo/local-role.sh show
  3. Run active-core / backup-core / edge-a / edge-b in separate terminals
EOF
}

set_defaults() {
  DEMO_ACTIVE_CORE_HOST="${DEMO_ACTIVE_CORE_HOST:-127.0.0.1}"
  DEMO_ACTIVE_CORE_PORT="${DEMO_ACTIVE_CORE_PORT:-1883}"
  DEMO_BACKUP_CORE_HOST="${DEMO_BACKUP_CORE_HOST:-127.0.0.1}"
  DEMO_BACKUP_CORE_PORT="${DEMO_BACKUP_CORE_PORT:-1884}"
  DEMO_EDGE_A_HOST="${DEMO_EDGE_A_HOST:-127.0.0.1}"
  DEMO_EDGE_A_PORT="${DEMO_EDGE_A_PORT:-2883}"
  DEMO_EDGE_B_HOST="${DEMO_EDGE_B_HOST:-127.0.0.1}"
  DEMO_EDGE_B_PORT="${DEMO_EDGE_B_PORT:-3883}"
  DEMO_BUILD_DIR="${DEMO_BUILD_DIR:-$ROOT_DIR/broker/build}"
}

load_env() {
  if [[ -f "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
  set_defaults
}

require_binary() {
  local path="$1"
  [[ -x "$path" ]] || die "missing executable: $path"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

write_env_file() {
  mkdir -p "$SCRIPT_DIR"
  cat >"$ENV_FILE" <<EOF
# Generated by ./demo/local-role.sh init
# You usually only need to edit the core/backup values.

DEMO_ACTIVE_CORE_HOST=$DEMO_ACTIVE_CORE_HOST
DEMO_ACTIVE_CORE_PORT=$DEMO_ACTIVE_CORE_PORT

DEMO_BACKUP_CORE_HOST=$DEMO_BACKUP_CORE_HOST
DEMO_BACKUP_CORE_PORT=$DEMO_BACKUP_CORE_PORT

DEMO_EDGE_A_HOST=$DEMO_EDGE_A_HOST
DEMO_EDGE_A_PORT=$DEMO_EDGE_A_PORT

DEMO_EDGE_B_HOST=$DEMO_EDGE_B_HOST
DEMO_EDGE_B_PORT=$DEMO_EDGE_B_PORT
EOF
}

show_config() {
  load_env
  printf 'ENV_FILE=%s\n' "$ENV_FILE"
  printf 'ACTIVE_CORE=%s:%s\n' "$DEMO_ACTIVE_CORE_HOST" "$DEMO_ACTIVE_CORE_PORT"
  printf 'BACKUP_CORE=%s:%s\n' "$DEMO_BACKUP_CORE_HOST" "$DEMO_BACKUP_CORE_PORT"
  printf 'EDGE_A_LOCAL=%s:%s\n' "$DEMO_EDGE_A_HOST" "$DEMO_EDGE_A_PORT"
  printf 'EDGE_B_LOCAL=%s:%s\n' "$DEMO_EDGE_B_HOST" "$DEMO_EDGE_B_PORT"
  printf '\n'
  printf 'Commands:\n'
  printf '  %s\n' "./demo/local-role.sh active-core"
  printf '  %s\n' "./demo/local-role.sh backup-core"
  printf '  %s\n' "./demo/local-role.sh edge-a"
  printf '  %s\n' "./demo/local-role.sh edge-b"
  printf '  %s\n' "./demo/local-role.sh active-sub"
  printf '  %s\n' "./demo/local-role.sh backup-sub"
}

cmd_init() {
  if [[ -f "$EXAMPLE_ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$EXAMPLE_ENV_FILE"
    set +a
  fi
  set_defaults

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --active-host)
        DEMO_ACTIVE_CORE_HOST="$2"
        shift 2
        ;;
      --active-port)
        DEMO_ACTIVE_CORE_PORT="$2"
        shift 2
        ;;
      --backup-host)
        DEMO_BACKUP_CORE_HOST="$2"
        shift 2
        ;;
      --backup-port)
        DEMO_BACKUP_CORE_PORT="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown init option: $1"
        ;;
    esac
  done

  write_env_file
  info "wrote demo config to $ENV_FILE"
  show_config
}

run_active_core() {
  load_env
  require_binary "$DEMO_BUILD_DIR/core_broker"
  exec "$DEMO_BUILD_DIR/core_broker" \
    "$DEMO_ACTIVE_CORE_HOST" "$DEMO_ACTIVE_CORE_PORT"
}

run_backup_core() {
  load_env
  require_binary "$DEMO_BUILD_DIR/core_broker"
  exec "$DEMO_BUILD_DIR/core_broker" \
    "$DEMO_BACKUP_CORE_HOST" "$DEMO_BACKUP_CORE_PORT" \
    "$DEMO_ACTIVE_CORE_HOST" "$DEMO_ACTIVE_CORE_PORT"
}

run_edge_a() {
  load_env
  require_binary "$DEMO_BUILD_DIR/edge_broker"
  exec "$DEMO_BUILD_DIR/edge_broker" \
    "$DEMO_EDGE_A_HOST" "$DEMO_EDGE_A_PORT" \
    "$DEMO_ACTIVE_CORE_HOST" "$DEMO_ACTIVE_CORE_PORT" \
    "$DEMO_BACKUP_CORE_HOST" "$DEMO_BACKUP_CORE_PORT"
}

run_edge_b() {
  load_env
  require_binary "$DEMO_BUILD_DIR/edge_broker"
  exec "$DEMO_BUILD_DIR/edge_broker" \
    "$DEMO_EDGE_B_HOST" "$DEMO_EDGE_B_PORT" \
    "$DEMO_ACTIVE_CORE_HOST" "$DEMO_ACTIVE_CORE_PORT" \
    "$DEMO_BACKUP_CORE_HOST" "$DEMO_BACKUP_CORE_PORT"
}

run_active_sub() {
  load_env
  require_cmd mosquitto_sub
  exec mosquitto_sub \
    -h "$DEMO_ACTIVE_CORE_HOST" -p "$DEMO_ACTIVE_CORE_PORT" -v \
    -t 'campus/#' \
    -t '_core/#'
}

run_backup_sub() {
  load_env
  require_cmd mosquitto_sub
  exec mosquitto_sub \
    -h "$DEMO_BACKUP_CORE_HOST" -p "$DEMO_BACKUP_CORE_PORT" -v \
    -t 'campus/#' \
    -t '_core/#'
}

clear_retained() {
  load_env
  require_cmd mosquitto_pub

  mosquitto_pub -h "$DEMO_ACTIVE_CORE_HOST" -p "$DEMO_ACTIVE_CORE_PORT" -t campus/monitor/topology -n -r
  mosquitto_pub -h "$DEMO_ACTIVE_CORE_HOST" -p "$DEMO_ACTIVE_CORE_PORT" -t _core/sync/connection_table -n -r
  mosquitto_pub -h "$DEMO_BACKUP_CORE_HOST" -p "$DEMO_BACKUP_CORE_PORT" -t campus/monitor/topology -n -r
  mosquitto_pub -h "$DEMO_BACKUP_CORE_HOST" -p "$DEMO_BACKUP_CORE_PORT" -t _core/sync/connection_table -n -r
  info "cleared retained topology on active/backup brokers"
}

case "${1:-show}" in
  init)
    shift
    cmd_init "$@"
    ;;
  show)
    show_config
    ;;
  active-core)
    run_active_core
    ;;
  backup-core)
    run_backup_core
    ;;
  edge-a)
    run_edge_a
    ;;
  edge-b)
    run_edge_b
    ;;
  active-sub)
    run_active_sub
    ;;
  backup-sub)
    run_backup_sub
    ;;
  clear-retained)
    clear_retained
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
